server:
  rate_limit: 100
  http:
    enabled: true
    port: 3476
    tls:
      enabled: false

logger:
  level: info

profiler:
  enabled: false

service:
  circuit_breaker: true
  watch:
    enabled: true

authn:
  enabled: true
  method: preshared
  preshared:
    keys: [THIS_IS_MY_SECRET_KEY]

database:
  engine: postgres
  auto_migrate: false
  max_open_connections: 20
  max_idle_connections: 1
  max_connection_lifetime: 300s
  max_connection_idle_time: 60s
  garbage_collection:
    enabled: true
    interval: 200h
    window: 200h
    timeout: 5m

distributed:
  enabled: false